name:                compose
version:             0.1.0.0
github:              "ohri-anurag/compose"
license:             GPL
author:              "Anurag Ohri"
maintainer:          "anuragohri92@gmail.com"
copyright:           "2020 Author Ohri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ohri-anurag/compose#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- binary
- vector
- safe

library:
  source-dirs: src

executables:
  compose:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compose

tests:
  compose-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compose
